name: API tests
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci .
    - name: Start app
      run: docker run --detach --name nombre_contenedor islasgeci make start
    - name: Run API tests
      run: docker exec nombre_contenedor make tests_api
